--USE TECHCONNECTDB;

--CREATE TABLE SocialMediaTypes(
--Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
--Type NVARCHAR(100) NOT NULL UNIQUE,
--ImageUrl NVARCHAR(255)
--);

--CREATE TABLE SocialLinks(
--Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
--UserProfileId INT NOT NULL FOREIGN KEY REFERENCES UserProfiles(USERID),
--Link NVARCHAR(255),
--SocialMediaTypeId INT NOT NULL FOREIGN KEY REFERENCES SocialMediaTypes(Id),
--CONSTRAINT FK_UserProfileId FOREIGN KEY (UserProfileId) REFERENCES UserProfiles(USERID)
--)